# Generated by Django 5.2.6 on 2026-01-07 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicalreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=250)),
                ('startime', models.CharField(max_length=100)),
                ('endtime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='audio_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=100)),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuser', to=settings.AUTH_USER_MODEL)),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expert_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guidline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guidline', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expert_table')),
                ('MEDICALREPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicalreport')),
            ],
        ),
        migrations.CreateModel(
            name='Parent_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feedback', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parent_table')),
            ],
        ),
        migrations.CreateModel(
            name='Attend_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=100)),
                ('mark', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('QUESTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question_table')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_percent', models.CharField(max_length=100)),
                ('mark', models.CharField(max_length=100)),
                ('solving_time', models.CharField(max_length=100)),
                ('prediction', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('ATTENDTABLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.attend_table')),
            ],
        ),
        migrations.CreateModel(
            name='Student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=300)),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parent_table')),
            ],
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table'),
        ),
        migrations.AddField(
            model_name='attend_table',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table'),
        ),
        migrations.CreateModel(
            name='Studymaterial_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=200)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expert_table')),
            ],
        ),
        migrations.CreateModel(
            name='Test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=100)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expert_table')),
            ],
        ),
        migrations.AddField(
            model_name='question_table',
            name='TEST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.test_table'),
        ),
        migrations.CreateModel(
            name='Tips_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tips', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expert_table')),
            ],
        ),
    ]
